name: "Build Code"

on:
  pull_request:
    branches:
      - dev
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_NAME: "comments-api"

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # TO-DO: write unit tests and execute them before building docker image
      # - name: Configure pipeline values
      #   id: pipeline_config
      #   run: |
      #     cd devops_helper_scripts
      #     pip install boto3
      #     python3 configure_pipeline_values.py
